-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.NAME FROM ANIMAL_INS 
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME>ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME ASC;

------------------------------

SELECT a.ANIMAL_ID,a.NAME FROM ANIMAL_INS a
INNER JOIN ANIMAL_OUTS b
ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.DATETIME>b.DATETIME
ORDER BY a.DATETIME ASC;
