SELECT ANIMAL_TYPE,COUNT(ANIMAL_TYPE)"count" FROM ANIMAL_INS GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE ASC;

SELECT ANIMAL_TYPE,COUNT(*)"count" FROM ANIMAL_INS GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE ASC;
